# require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'maestrano-connector-rails.gemspec'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'spec/**/*'
    - 'template/*'
    - 'lib/generators/connector/templates/*'
    - 'lib/maestrano_connector_rails/factories.rb'

# Enabled disabled Cops
Style/CollectionMethods:
  Enabled: true

Metrics/LineLength:
  Max: 320

Metrics/MethodLength:
  Max: 50

Layout/IndentationConsistency:
  EnforcedStyle: rails

# Missing top-level class documentation comment
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Space inside braces => only for blocks (not for literal)
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Checks for unused block arguments
Lint/UnusedBlockArgument:
  Enabled: false

# Checks for unused method arguments.
Lint/UnusedMethodArgument:
  Enabled: false

# RSpec/FilePath:
#   Exclude:
    # - 'spec/routing/**/*_routing_spec.rb'
